version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3000
      DATABASE_USER: sa
      DATABASE_PASSWORD: Passw1rd!
      DATABASE_NAME: bookdb
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  db:
    image: postgres:latest
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: sa
      DATABASE_PASSWORD: Passw1rd!
      DATABASE_NAME: bookdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: